env: sandbox

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "250Mi"
    cpu: "50m"
  limits:
    cpu: "200m"
    memory: "1000Mi"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 300
  cpuPercentage: 200
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

sample:
  service:
    baseUrl: "http://localhost:8080"
    path: "/samples"

verbose: true
