// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"io/ioutil"

	"github.com/ONSdigital/ras-rm-sample/file-uploader/config"
	"github.com/ONSdigital/ras-rm-sample/file-uploader/file"
	"gopkg.in/yaml.v2"
)

// Injectors from injector.go:

func Inject() file.FileProcessor {
	config := ConfigSetup()
	fileProcessor := NewFileProcessor(config)
	return fileProcessor
}

// injector.go:

func ConfigSetup() config.Config {
	file2, err := ioutil.ReadFile("application.yaml")
	if err != nil {
		panic(err)
	}
	config2 := &config.Config{}
	yaml.Unmarshal(file2, &config2)
	return *config2
}

func NewFileProcessor(config2 config.Config) file.FileProcessor {
	return file.FileProcessor{Config: config2}
}
